title: JU Kod
description: Competitive programming study group at JTH / JU
source: /
markdown: GFM

theme: jekyll-theme-slate
# other nice-looking themes:
#   theme: jekyll-theme-cayman   # greenish
#   theme: jekyll-theme-hacker   # dark monospaced green
#   theme: jekyll-theme-midnight # dark background
#   theme: jekyll-theme-slate    # grey / gray
#   theme: jekyll-theme-leap-day # blue-and-yellow
# full list: https://pages.github.com/themes/

plugins:
  - jemoji

github:
  is_project_page: false # disables the "view on GitHub" button
